#!/usr/bin/env python

import sys, os
import os.path as osp
from datetime import date


if sys.argv[1]!='--error':

    target = osp.join('/results/boinc2docker')
    os.system('mv %s %s'%(' '.join(sys.argv[1:]),target))
