#!/usr/bin/env python

import os, sys
import tarfile

extension = '.txt'
extract_flag = False
result_dir = '/home/boincadm/project/tmp_models/'
models_temp_dir = os.path.join(result_dir, 'models')
result_path = sys.argv[1]
result_id = sys.argv[2]

def check_and_extract():
	print('Extracting ', result_id, ' result')
	with tarfile.open(result_path) as tar:
		members = tar.getmembers()
		for member in members:
			if member.name.endswith(extension):
				tar.extract(member, models_temp_dir)
				os.rename(os.path.join(models_temp_dir, member.name),
					os.path.join(models_temp_dir, result_id+'_result'+extension))
				extract_flag = True
		if extract_flag:
			print('Model was extracted')
		else:
			print('There is no model file!')
			return 0

check_and_extract()
