#!/usr/bin/env python
import os, sys

min_quorum = sys.argv[1]
target = sys.argv[2]

os.system("bin/boinc2docker_create_work.py --rsc_disk_bound 2147483648 --rsc_memory_bound 4831838208 " +\
	"--min_quorum {0} --target_nresults {1} --max_success_results {2} --max_total_results 200 --max_error_results 200 ozon67/cryo-client:test"
            .format(min_quorum, target, int(target)+5))
